### ISSUE TITLE
Tech Talk: Gatsby Static Site Generator

### ISSUE THREAD

**Issue by master12** [novajs/talks#1]
**Your Name:** Jeff Keene 
**Your twitter handle:** [optional]  
**A few words about yourself:** 
I learned how to program from my mother in second grade and thought it was fun. I was lucky enough to turn my hobby into a career.  I have been programming since Java 1.3 and JSP 1.0. Started with javascript and have circled back to what is my favorite language to use. 

Currently working for the DOI(Dept of Interior) on a data analytics site that uses D3 for data visualizations and recently change from jekyll/webcomponents to using gatsby/react. Gatsby is based on javascript/react/graphql and thought it might be interesting to folks to learn about how to generate a static site. I know I learned a lot.

Also Star Wars wishes they could be as cool as Star Trek.

**Talk title:** No title. Just Gatsby for now

**Talk abstract:**  
So recently we gave a talk on why we switched from Jekyll to Gatsby however for this group I can focus on just gatsby and the various features it provides for taking data from excel to graphql to react to d3 to the web. I can also talk about the reasons for us using a static site and leveraging markdown with custom react components embedded in the markdown. 

Anyway you mentioned you have trouble getting speakers so I though I would throw this out there to gauge interest.

**Expected length:** 30 to 45 mins

**Available months:** May, July

_We meet on the second Thursday of the month generally. You can use this handy-dandy list to check dates:_

- [X] NOVAJS[65] Wed May 1 2019
- [ ] NOVAJS[66] Wed Jun 5 2019
- [X] NOVAJS[67] Wed Jul 3 2019
- [ ] NOVAJS[68] Wed Aug 7 2019
- [ ] NOVAJS[69] Wed Sep 4 2019
- [ ] NOVAJS[70] Wed Oct 2 2019
- [ ] NOVAJS[71] Wed Nov 6 2019
- [ ] NOVAJS[71] Wed Dec 4 2019

**Comment by mcrowder65** [comment]
Hey Jeff! 👋 Do you prefer to do May or July?

**Comment by mcrowder65** [comment]
Hey Jeff! Just wanted to follow up, we can put you in for May if you want to speak then?

**Comment by mcrowder65** [comment]
Hey Jeff! Just wanted to follow up, we can put you in for May if you want to speak then?

**Comment by mcrowder65** [comment]
Hey Jeff! We’re still interested in you giving this talk if you want to!

**Comment by master12** [comment]
So sorry I didnt get the notifications for this. I am available whenever you want to schedule this.

**Comment by mcrowder65** [comment]
No problem! Can I book you for October?

**Comment by master12** [comment]
That should work.

**Comment by mcrowder65** [comment]
Hey Jeff, are you still good for October? Just wanted to follow up.  If you do, could I get a more ironed out abstract?

**Comment by mcrowder65** [comment]
Hey Jeff, are you still good for October? Just wanted to follow up.  If you are, could I get a more ironed out abstract?

**Comment by master12** [comment]
Yes, I am good. How long is the presentation? Got it 45 mins

**Comment by master12** [comment]
Here is what I am thinking so far:

Intro: **5 mins**
- What is Gatsby? 
- What is JAMStack?
- Other available static site generators.

Case Study:DOI-ONRR Data Portal: **5 mins**
-  Background
-  Why we chose gatsby?

Gatsby Simple Site Example (Generate a few basic pages with Gatsby): **15 mins**
- Basic page and site structure
- Introduce Plugins/gastby-config
- Gatsby API/ gatsby-node
- Pages created with templates
- Pages created using Markdown
- React components in Markdown

Gatsby Graphql: **10 mins**
- Add a few data sources
- Review graphiql explorer
- Add graphql query to a page and/or component

Case Study Continued: DOI-ONRR: **2 Mins**
- How we use gatsby in our environment
- Lessons Learned

Conclusion/Wrapup: **1 min**

**Comment by mcrowder65** [comment]
This all looks great, could we get the abstract as a one paragraph summary for the meetup page? Thanks!

**Comment by mcrowder65** [comment]
Hey Jeff! The sooner we could get the abstract that would be great so we can spread the word, thanks!

**Comment by master12** [comment]
Well work on that today and get it to you before the EOB

**Comment by master12** [comment]
Government websites and apps aren’t generally known for using the latest tech stacks, but our small team wanted to change that. Our open data site weaves together data from multiple sources, powering visualizations, filterable tables, and supporting content. In an effort to improve site performance and maintainability – while reducing our technical debt – we turned to the JAMstack, specifically GatsbyJS. Using React and GraphQL, Gatsby allowed us to create a modern, flexible component architecture. We can now query data from virtually any source with our GraphQL schema, and we’ve transformed our data maintenance workflow to allow anyone, not just developers, to update the site.

This talk will include a basic introduction to the JAMstack, building a site with Gatsby and lessons learned from our project.

**Comment by mcrowder65** [comment]
https://www.meetup.com/NoVaJS/events/264599410

**Comment by master12** [comment]
Hey Matt, This is for October ?

**Comment by mcrowder65** [comment]
haha woops! I edited it for next October 2nd, LMK if that doesn't work!

**Comment by master12** [comment]
Phew. Thats Perfect. Thanks.

Working on the Prez this weekend so no worries.

**Comment by mcrowder65** [comment]
Perfect! Let me know if you have any questions or need any help or feedback. Happy to help

**Comment by mcrowder65** [comment]
Hey Jeff! Can you email me at mcrowder65@gmail.com I’d like to exchange numbers so you can call me tonight if you need to
