### ISSUE TITLE
Tech Talk: Storybook UI testing you will love

### ISSUE THREAD

**Issue by cogwizzle** [novajs/talks#2]
**Your Name:**  Joseph Fehrman
**Your twitter handle:** joseph_fehrman  
**A few words about yourself:** Software Engineer from Fredericksburg Virginia.  I work in Richmond VA at UDig as a software consultant.  Just a nerd who loves learning new things and likes to write code for fun.  When I'm not learning new things I'm currently trying to get back into shape.
**Talk title:** Storybook UI testing you will love

**Talk abstract:**  
Are you working with Angular or React and find that your automated test just isn’t enough?  Your test pass, but something could still be off with the appearance of the component.  Wouldn’t you like a place where you could see all of your components independently and check them for consistency?  Sometimes it helps to be able to interact with the component.  We’ve got you covered!  Come explore the ins and outs of Storybook, a user interface development environment you are going to love!

**Expected length:** 30-40 mins

**Available months:** June and on?  Just let me know a day.  I'm flexible.

_We meet on the first Wednesday of the month generally. You can use this handy-dandy list to check dates:_

- [ ] NOVAJS[65] Wed May 1 2019
- [x] NOVAJS[66] Wed Jun 5 2019
- [ ] NOVAJS[67] Wed Jul 3 2019
- [ ] NOVAJS[68] Wed Aug 7 2019
- [ ] NOVAJS[69] Wed Sep 4 2019
- [ ] NOVAJS[70] Wed Oct 2 2019
- [ ] NOVAJS[71] Wed Nov 6 2019
- [ ] NOVAJS[71] Wed Dec 4 2019

**Comment by mcrowder65** [comment]
Hey Joe! 👋I want to book you for June 5, can you confirm with me for that?

**Comment by cogwizzle** [comment]
Yeah!  June 5th is good with me.
