### ISSUE TITLE
Tech Talk: GraphQL Basics: What you should know

### ISSUE THREAD

**Issue by mftaher** [novajs/talks#3]
**Your Name:** Fazle Taher  
**Your twitter handle:** ftaher  
**A few words about yourself:** Fazle is Director of Software Engineering at Demosphere that provides SaaS solution for organized youth sports. He enjoys learning about new technologies, codes in Ruby, NodeJS, React and MongoDB. Other times he is playing with his son and two daughters, a Liverpool fan and plays soccer in Fairfax area.

**Talk title:** GraphQL Basics: What you should know

**Talk abstract:**  
Jack is a frontend dev and Jill is a backend dev. One day Jill changed their app’s API in the back end, which caused the client to report Jack an error about a strange “infinite loading circle”. Jack discovers the recent change Jill made, and she sends him documentation from Swagger to send him on his merry way back to the client.

Instead of documentation handoffs, what if Jack and Jill could communicate through a document  that was codified? Or it was available to Jack right away and the code Jill developed would be graceful, versioned, maintained, and validated? What if writing that API schema described relationships between different API endpoints?

This talk is a brief introduction to GraphQL API development, its usage, application in different scenarios, and of course; how GraphQL can help Jack and Jill.

**Expected length:** 30-45mins

**Available months:** August onwards

_We meet on the first Wednesday of the month generally. You can use this handy-dandy list to check dates:_

- [ ] NOVAJS[65] Wed May 1 2019
- [ ] NOVAJS[66] Wed Jun 5 2019
- [ ] NOVAJS[67] Wed Jul 3 2019
- [X] NOVAJS[68] Wed Aug 7 2019
- [X] NOVAJS[69] Wed Sep 4 2019
- [ ] NOVAJS[70] Wed Oct 2 2019
- [ ] NOVAJS[71] Wed Nov 6 2019
- [ ] NOVAJS[71] Wed Dec 4 2019

**Comment by mcrowder65** [comment]
Hey Fazle! Can we get you booked for the September meetup?

**Comment by mftaher** [comment]
Yes sure

**Comment by mcrowder65** [comment]
Ok awesome, I'll reach out to you in early August to get it booked and confirm that you can speak.

**Comment by mcrowder65** [comment]
Hey Fazle! Are you still good for us to book you for the September 4th meetup? But before we do that, can i get a more ironed out abstract? Yours is pretty sparse at the moment, let me know if you need help with that.

**Comment by mftaher** [comment]
Apology for the delayed reply. Yes, I’ll be giving the talk. I’ll update the talk summary soon.

Thanks

**Comment by mftaher** [comment]
Hey Matt, I updated the summary. If it still doesn't work, I could use some help.

**Comment by mcrowder65** [comment]
This is great, I'll get this meetup posted tomorrow and I'll announce it at the meetup on wednesday! thanks!

**Comment by mcrowder65** [comment]
https://www.meetup.com/NoVaJS/events/263954291

**Comment by mcrowder65** [comment]
Hey Fazle! Could you email me at mcrowder65 at gmail.com ? I would like to exchange phone numbers for the day of and discuss logistics, etc. thanks!

**Comment by mcrowder65** [comment]
Thanks again Fazle! It was a great talk.
