### ISSUE TITLE
Yarn Workspaces.

### ISSUE THREAD

**Issue by subtle42** [novajs/talks#4]
Daniel Gottlieb, daniel.gottlieb@plus3it.com

A developer of 10 years. Always looking at new tools to try to make life a little easier. An avid comic reader in my spare time.

Talk title: Yarn workspaces, One project to rules them all!

**Talk abstract:**  
In many large projects it is normal to have several repositories. This makes sense in most use cases. But sometimes there is that nagging voice saying man this would be easier if it was all in one project. Yarn has the ability to create workspaces that let you bring several projects under one roof. This can work well with test, UI, mobile repos. The talk will be about how to setup Yarn workspaces, use cases and limitations.

**Expected length:** 30-45 min

**Available months:** Nov-Dec

- [x] NOVAJS[71] Wed Nov 6 2019
- [x] NOVAJS[71] Wed Dec 4 2019

**Comment by mcrowder65** [comment]
Thanks for submitting Daniel, would you prefer to speak in November or December?
